# Generated by Django 4.1.7 on 2023-03-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0002_articulo_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
