# Generated by Django 4.1.7 on 2023-03-30 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDjango', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('subtitulo', models.CharField(max_length=60)),
                ('cuerpo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
